version: '3.8'

services:
  activity-service:
    build:
      context: ./ActivityService
    ports:
      - "8082:8082"
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-activity
      MYSQL_DB_PORT: 3307  # Dit moet overeenkomen met mysql-activity service

  mood-service:
    build:
      context: ./MoodServicee  # Let op: controleer of deze naam correct is.
    ports:
      - "8080:8080"
    environment:
      MONGODB_HOST: mongo-mood
      MONGODB_PORT: 27017

  recommendation-service:
    build:
      context: ./RecommendationService
    ports:
      - "8081:8081"
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-recommendation
      MYSQL_DB_PORT: 3308  # Dit moet overeenkomen met mysql-recommendation service

  user-service:
    build:
      context: ./UserService
    ports:
      - "8083:8083"
    environment:
      MONGODB_HOST: mongo-user
      MONGODB_PORT: 27017  # Dit moet consistent zijn met de MongoDB-service

  mysql-activity:
    image: mysql:latest
    ports:
      - "3307:3306"
    volumes:
      - mysql_activity_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  mongo-mood:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_mood_data:/data/db

  mysql-recommendation:
    image: mysql:latest
    ports:
      - "3308:3306"  # Expose poort 3306 voor de buitenwereld, maar intern draait het op 3306
    volumes:
      - mysql_recommendation_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  mongo-user:
    image: mongo:latest
    ports:
      - "28018:27017"  # Dit is nu consistent met de MongoDB-service
    volumes:
      - mongodb_user_data:/data/db

volumes:
  mysql_activity_data:
  mongodb_mood_data:
  mysql_recommendation_data:
  mongodb_user_data:
