version: '3.8'

services:
  # MongoDB voor MoodService
  mongo-mood:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_mood_data:/data/db

  # MongoDB voor UserService
  mongo-user:
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - mongodb_user_data:/data/db

  # MySQL voor ActivityService
  mysql-activity:
    image: mysql:latest
    ports:
      - 3307:3306
    volumes:
      - mysql_activity_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  # MySQL voor RecommendationService
  mysql-recommendation:
    image: mysql:latest
    ports:
      - 3308:3306
    volumes:
      - mysql_recommendation_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  # ActivityService
  activity-service:
    depends_on:
      - mysql-activity
    image: siebegios/activity-service
    ports:
      - 8082:8082
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-activity
      MYSQL_DB_PORT: 3306

  # MoodService
  mood-service:
    depends_on:
      - mongo-mood
    image: siebegios/mood-service
    ports:
      - 8080:8080
    environment:
      MONGO_DB_HOST: mongo-mood
      MONGO_DB_PORT: 27017

  # UserService
  user-service:
    depends_on:
      - mongo-user
    image: siebegios/user-service
    ports:
      - 8083:8083
    environment:
      MONGO_DB_HOST: mongo-user
      MONGO_DB_PORT: 27017

  # RecommendationService
  recommendation-service:
    depends_on:
      - activity-service
      - user-service
      - mood-service
      - mysql-recommendation
    image: siebegios/recommendation-service
    ports:
      - 8081:8081
    environment:
      ACTIVITY_SERVICE_BASEURL: activity-service:8082
      MOOD_SERVICE_BASEURL: mood-service:8080
      USER_SERVICE_BASEURL: user-service:8083
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-recommendation
      MYSQL_DB_PORT: 3306

  # API Gateway
  api-gateway:
    image: siebegios/api-gateway
    ports:
      - 8085:8080  # Externe toegang op poort 8085
    depends_on:
      - activity-service
      - mood-service
      - user-service
      - recommendation-service
    links:
      - activity-service
      - mood-service
      - user-service
      - recommendation-service
    environment:
      RECOMMENDATION_SERVICE_BASEURL: recommendation-service:8081
      MOOD_SERVICE_BASEURL: mood-service:8080
      ACTIVITY_SERVICE_BASEURL: activity-service:8082
      USER_SERVICE_BASEURL: user-service:8083

volumes:
  mongodb_user_data:
  mongodb_mood_data:
  mysql_activity_data:
  mysql_recommendation_data:

