server:
  port: 8085

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 10          # Number of requests per second allowed
              burstCapacity: 20          # Max number of requests allowed in a burst
      routes:
        # Recommendation Service
        - id: recommendation-service
          uri: http://${RECOMMENDATION_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/api/recommendations/{userid}
            - Method=GET
          filters:
            - SetPath=/api/recommendations/{userid}
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Origin
                value: "http://localhost:3000"
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Methods
                value: "GET, POST, PUT, DELETE"
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Headers
                value: "Content-Type, Authorization"

        # Mood Service
        - id: mood-service-get
          uri: http://${MOOD_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/api/mood
            - Method=GET
          filters:
            - SetPath=/api/mood/all

        - id: mood-service-post
          uri: http://${MOOD_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/api/mood
            - Method=POST
          filters:
            - SetPath=/api/mood

        - id: mood-service-put
          uri: http://${MOOD_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/api/mood/{id}
            - Method=PUT
          filters:
            - SetPath=/api/mood/{id}

        - id: mood-service-delete
          uri: http://${MOOD_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/api/mood/{id}
            - Method=DELETE
          filters:
            - SetPath=/api/mood/{id}

        # Activity Service
        - id: activity-service-get
          uri: http://${ACTIVITY_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/api/activity
            - Method=GET
          filters:
            - SetPath=/api/activity

        - id: activity-service-post
          uri: http://${ACTIVITY_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/api/activity
            - Method=POST
          filters:
            - SetPath=/api/activity

        - id: activity-service-put
          uri: http://${ACTIVITY_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/api/activity/{id}
            - Method=PUT
          filters:
            - SetPath=/api/activity/{id}

        - id: activity-service-delete
          uri: http://${ACTIVITY_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/api/activity/{id}
            - Method=DELETE
          filters:
            - SetPath=/api/activity/{id}

        # User Service
        - id: user-service-get
          uri: http://${USER_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/api/user
            - Method=GET
          filters:
            - SetPath=/api/user

        - id: user-service-getuser
          uri: http://${USER_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/api/user/{id}
            - Method=GET
          filters:
            - SetPath=/api/user/{id}

        - id: user-service-post
          uri: http://${USER_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/api/user
            - Method=POST
          filters:
            - SetPath=/api/user

        - id: user-service-put
          uri: http://${USER_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/api/user/{id}
            - Method=PUT
          filters:
            - SetPath=/api/user/{id}

        - id: user-service-delete
          uri: http://${USER_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/api/user/{id}
            - Method=DELETE
          filters:
            - SetPath=/api/user/{id}
