apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activity-service
  template:
    metadata:
      labels:
        app: activity-service
    spec:
      containers:
        - name: activity-service
          image: siebegios/activity-service
          env:
            - name: MYSQL_DB_USERNAME
              value: root
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-activity-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DB_HOST
              value: mysql-activity
            - name: MYSQL_DB_PORT
              value: "3306"
          ports:
            - containerPort: 8082