apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-activity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-activity
  template:
    metadata:
      labels:
        app: mysql-activity
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          envFrom:
            - secretRef:
                name: mysql-activity-secret
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-activity-pvc